[tool.nx]
autoActivate = true

[tool.poetry]
name = "@avbodh/source"
version = "1.0.0"
description = ""
authors = [ ]
license = "Proprietary"
readme = "README.md"
package-mode = false

  [tool.poetry.dependencies]
  python = ">=3.12,<4.0"
  langchain-huggingface = "^1.2.2"
  pymongo = "^4.17.0"
  fastapi = {extras = ["standard"], version = "^0.141.1"}
  langgraph = "^1.2.11"
  langchain = "^1.3.15"
  motor = "^3.7.1"
  aio-pika = "^10.0.1"
  langchain-groq = "^1.1.3"
  numpy = "^2.5.2"
  pinecone = "^9.1.0"

    [tool.poetry.dependencies.avbodh-tools]
    path = "libs/python"
    develop = true

[build-system]
requires = [ "poetry-core==1.1.0" ]
build-backend = "poetry.core.masonry.api"
