import dotenv from 'dotenv';
import path from 'path';

import fs from 'fs';
process.env.DOTENV_QUIET = 'true';

// Nx can run this from the workspace root or the app root, so we check both!
const envPaths = [
  path.join(process.cwd(), '.env'),
  path.join(process.cwd(), 'app/auth/.env')
];
for (const p of envPaths) {
  if (fs.existsSync(p)) {
    dotenv.config({ path: p });
    break;
  }
}

function requireEnv(key: string): string {
  const value = process.env[key];
  if (!value) {
    throw new Error(`Missing required environment variable: "${key}"`);
  }
  return value;
}

export const {
  NOMIC_API_KEY,
  PORT,
  SUBMIT_CHAPTER_WISE_PORT,
  JWT_SECRET_ACCESS_TOKEN,
  JWT_TEMP_EXPIRES_IN_ACCESS_TOKEN,
  JWT_ALGORITHM_ACCESS_TOKEN,
  JWT_SECRET_REFERSH_TOKEN,
  JWT_TEMP_EXPIRES_IN_REFERSH_TOKEN,
  JWT_ALGORITHM_REFERSH_TOKEN,
  DATABASE_URL,
  DATABASE_URL_PRODUCTION,
  DATABASE_REPICA_URL,
  REDIS_HOST,
  REDIS_PORT,
  GOOGLE_AUTH_PASSWORD,
  INTERNAL_API_SECRET,
  OTP_EXPIRE_TIME,
  SALT_ROUND,
  MAX_ATTEMENTS,
  WINDOW_SIZE,
  REDIS_PASSWORD,
  REDIS_USERNAME,
  GEMINI_API_KEY,
  BACKBLAZE_REGION,
  BACKBLAZE_ENDPOINT,
  BUCKET_NAME,
  IMAGE_EXPIRE_TIME,
  BACKBLAZE_KEY_ID,
  BACKBLAZE_APP_KEY,
  IV_LENGTH,
  ENCRYPTION_KEY,
  BUCKET_ID,
  IMAGE_WORKER_BASE_URL,
  EMAIL_WORKER_PORT,
  UPDATE_WORKER_PORT,
  WATCHDOG_PORT,
  WATCHDOG_INTERVAL,
  WATCHDOG_INACTIVITY_THRESHOLD_SEC,
  EVALUATION_WORKER_PORT,
  STUDENT_TEST_ANALYTICS_WORKER_PORT,
  EMAIL_ADDING_WORKER_PORT,
  TOKEN_BUCKET_CAPACITY,
  TOKEN_BUCKET_REFLIER,
  QUESTION_STORE_REDIS_URL,
  QUESTION_STORE_REDIS_PORT,
  QUESTION_STORE_REDIS_USERNAME,
  QUESTION_STORE_REDIS_HOST,
  QUESTION_STORE_REDIS_PASSWORD,
  GOOGLE_CLIENT_ID,
  REDIS_CACHE_EXPIRATION_SECONDS,
  REDIS_URL,
  QUEUE_PASSWORD,
  QUEUE_PORT,
  QUEUE_URL,
  QUEUE_HOST,
  QUEUE_EXCHANGE,
  QUEUE_ROUTING_EMAIL,
} = process.env;
